# Generated by Django 5.0.2 on 2024-02-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
