# Generated by Django 5.0.2 on 2024-02-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpost_description"),
        ("main", "0003_alter_category_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BlogPost",
            new_name="Post",
        ),
    ]
