# Generated by Django 5.0.2 on 2024-02-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_rename_blogpost_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
