# Generated by Django 5.0.2 on 2024-03-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(default="Steve Rios", max_length=50),
        ),
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
