# Generated by Django 5.0.2 on 2024-03-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_post_dislikes_post_eyes_post_shocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="meta_keywords",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
