# Generated by Django 5.0.2 on 2024-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="meta_keywords",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
