# Generated by Django 5.0.2 on 2024-04-07 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_alter_post_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="eyes",
            new_name="robots",
        ),
    ]
