# Generated by Django 5.0.2 on 2024-02-24 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="video.video",
            ),
        ),
    ]
