# Generated by Django 5.0.2 on 2024-02-28 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
